export enum GlobalColor {
    white = 3,
    black = 2,
    red = 7,
    darkRed = 13,
    green = 8,
    darkGreen = 14,
    blue = 9,
    darkBlue = 15,
    cyan = 10,
    darkCyan = 16,
    magenta = 11,
    darkMagenta = 17,
    yellow = 12,
    darkYellow = 18,
    gray = 5,
    darkGray = 4,
    lightGray = 6,
    transparent = 19,
    color0 = 0,
    color1 = 1,
}
