#pragma once

#include "QtCore/QObject/qobject_macro.h"

/*
    This macro adds common QAbstractItemDelete exported methods
 */

#ifndef QABSTRACTITEMDELEGATE_WRAPPED_METHODS_DECLARATION
#define QABSTRACTITEMDELEGATE_WRAPPED_METHODS_DECLARATION \
  QOBJECT_WRAPPED_METHODS_DECLARATION
#endif

#ifndef QABSTRACTITEMDELEGATE_WRAPPED_METHODS_EXPORT_DEFINE
#define QABSTRACTITEMDELEGATE_WRAPPED_METHODS_EXPORT_DEFINE(WrapName) \
  QOBJECT_WRAPPED_METHODS_EXPORT_DEFINE(WrapName)
#endif  // QABSTRACTITEMDELEGATE_WRAPPED_METHODS_EXPORT_DEFINE

#ifndef QABSTRACTITEMDELEGATE_SIGNALS
#define QABSTRACTITEMDELEGATE_SIGNALS QOBJECT_SIGNALS
#endif  // QABSTRACTITEMDELEGATE_SIGNALS
