export enum CursorShape {
    ArrowCursor = 0,
    UpArrowCursor = 1,
    CrossCursor = 2,
    WaitCursor = 3,
    IBeamCursor = 4,
    SizeVerCursor = 5,
    SizeHorCursor = 6,
    SizeBDiagCursor = 7,
    SizeFDiagCursor = 8,
    SizeAllCursor = 9,
    BlankCursor = 10,
    SplitVCursor = 11,
    SplitHCursor = 12,
    PointingHandCursor = 13,
    ForbiddenCursor = 14,
    OpenHandCursor = 17,
    ClosedHandCursor = 18,
    WhatsThisCursor = 15,
    BusyCursor = 16,
    DragMoveCursor = 20,
    DragCopyCursor = 19,
    DragLinkCursor = 21,
    BitmapCursor = 24,
}
